### ISSUE TITLE
Any luck on automating player transfers?

### ISSUE THREAD

**Issue by turner-prize** [azizfcb/azifpl#1]
Just wondering if you manged to automate the transfer of players during the game week with your package. I have a similar python package but the only thing I'm missing is the player transfers and would like to see if anyone has had success with this.

**Comment by azizfcb** [comment]
Could you please give a description.

Anyway, I'm starting to work on this package again before the season begins.

**Comment by azizfcb** [comment]
Now I get you. My idea of automated transfer is a method with two inputs : oldPlayerId and newPlayerId, it's output should be: success or fail with no funds error, max players of same team reached or different positions.

Give me a week.

**Comment by turner-prize** [comment]
Sound mate, no rush! I'm just having issues moving the cookies around once I'm logged in so I wanted to see how someone else did it. And the oldID/newID thing is exactly what I was thinking as well!

**Comment by turner-prize** [comment]
Managed to get this working in my python module so don't really need to keep this open, but best of luck you mate!
